owner: constructions-incongrues
repo: status-jeancloude

sites:
  - name: Carte Membre
    url: https://cartemembre.jeancloude.club
  - name: VIP
    url: https://vip.jeancloude.club

assignees:
  - trivoallan

status-website:
  cname: status.jeancloude.club
  name: Jean-Cloude
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  navbar:
    - title: Github
      href: https://github.com/constructions-incongrues/status-jeancloude/
    - title: Constructions
      href: https://status.constructions-incongrues.net
    - title: Interzone
      href: https://status.interzone.network
    - title: Jean-Cloude
      href: https://status.jeancloude.club
    - title: Pantagruweb
      href: https://status.pantagruweb.club
    - title: Pastis
      href: https://pastis-hosting.net
